### ISSUE TITLE
Cannot set split_sentences to "nonewlines"

### ISSUE THREAD

**Issue by Mistralys** [SC-Networks/deepl-api-connector#20]
Hello,

the `split_sentences` API parameter has three possible values:

"0" - off
"1" - on
"nonewlines" - do not split on newlines

See https://www.deepl.com/docs-api.html?part=xml#xml__newlines

However, internally, the package enforces the `TranslationConfigInterface::setSplitSentences` to accept only integer values, so the parameter cannot be set to "nonewlines".

**Comment by Mistralys** [comment]
A suggestion would be to use an Enum, like the other enums that already exist.

Something like this:

```php
declare(strict_types=1);

namespace Scn\DeeplApiConnector\Enum;

final class SplitNewlinesEnum
{
    public const ON = '1';
    public const OFF = '0';
    public const NONEWLINES = 'nownewlines';
}
```

**Comment by WorksDev** [comment]
@Mistralys Thanks for the note, fix is in progress.
