### ISSUE TITLE
Adding proxy support

### ISSUE THREAD

**Issue by Mistralys** [SC-Networks/deepl-api-connector#23]
Hello,

it is currently not possible to specify a proxy server to connect to the DeepL API. Guzzle itself allows specifying request options, but there are several ways to do this. I was going to create a fork to offer a solution, but I am unsure how you would prefer to implement this.

As far as I could see, there are two ways to specify a proxy via Guzzle options:

### When instantiating the Guzzle client 

In this case, the proxy is used for all requests.

```php
// DeeplClient.php line 71
public static function create($apiKey, array $guzzleOptions=array()): DeeplClientInterface
{
    return new DeeplClient(
        new \GuzzleHttp\Client($guzzleOptions),
        new Handler\DeeplRequestFactory($apiKey)
    );
}
```
Sadly enough, the Guzzle client does not offer any way to change the configuration once it has been instantiated (at least I could not find anything) - so it is not possible to configure a proxy after calling the `create()` method. 

This way is not very straightforward, because one has to know the exact format of the Guzzle options array.

### On each request 

Moving the proxy info here would allow adding a `DeeplClient::setProxy()` method, which would be way easier to understand. It would require integrating the proxy options into the `getBody()` method, so it is passed into the options parameter in the `executeRequest` method:

```php
// DeeplClient line 120
private function executeRequest(DeeplRequestHandlerInterface $requestHandler): \stdClass
{
    try {
        $response = $this->httpClient->request(
            $requestHandler->getMethod(),
            $requestHandler->getPath(),
            $requestHandler->getBody() // Include Guzzle options here
        );
```

## Config details

Details on the options that need to be passed to Guzzle for the proxy:

```php
// in the request options
$client->request(
    'GET', 
    '/path/to/api', 
    array(
        'proxy' => 'tcp://localhost:8125'
    )
);
```

```php
// when instantiating the client
$client = new Client(array(
    'proxy' => 'tcp://12.34.56.78:3128'
));
```

Info found here: https://stackoverflow.com/questions/32324893/set-proxy-in-guzzle#42034631

What do you think, how would you prefer to implement something like this?

Cheers!

**Comment by WorksDev** [comment]
Hi,

thanks for your feedback.

Currently I don't see any reason to add proxy support here, you already have the possibility if you don't use the ::create method.

In this case simply:

```
new DeeplClient(
 new GuzzelClient(['my' => 'Options']),
 new DeeplRequestFactory($apiKey) 
);
```

@usox what do you think?

**Comment by Mistralys** [comment]
Hah, I have to admit I did not think of that :) 

I can work with this solution. I agree that having a dedicated way to configure a proxy is only a nice to have in this case. Maybe just add it to the docs somewhere instead?

**Comment by usox** [comment]
+1 for adding it to docs.

Adding dedicated `guzzleparams` to the signature of the create-methods would bind the library to guzzle, so I guess this won't ever happen. 

We should consider to change the library to support PSR-18 instead of relying on guzzle - different users may use different http client libraries and we should provide a way, to pass an existing client instance (as long as it supports PSR-18) like in the example @WorksDev provided.

**Comment by WorksDev** [comment]
The documentation will be updated with version 3.0, also PSR-18 will be implemented. I already have a major patch in the works, but it will probably take a few more days.

**Comment by Mistralys** [comment]
Thanks everyone, already tested it, and it works.

**Comment by usox** [comment]
@Mistralys :+1:
