### ISSUE TITLE
Using the Deepl Free Api

### ISSUE THREAD

**Issue by evang522** [SC-Networks/deepl-api-connector#43]
Deepl's API has a free tier which uses another endpoint: namely `https://api-free.deepl.com/v2/`. See the distinction at the bottom of the page here: https://www.deepl.com/docs-api/accessing-the-api/api-versions/.

This is a great library and I think many would benefit from being able to use it with the free tier API. As far as I can tell, there only needs to be some dynamic switching between the request handlers' API endpoint based on provided configuration. If I have some time to work on this soon, I will. Just wanted to make an issue first in case someone knows something I don't. 

Thanks!

**Comment by WorksDev** [comment]
@evang552 thank you for your feedback. We will take it into account over the next few days.
