### ISSUE TITLE
Support glossaries

### ISSUE THREAD

**Issue by WorksDev** [SC-Networks/deepl-api-connector#47]

**Comment by Soetens** [comment]
This would be a great addition

**Comment by Ciloe** [comment]
Hi, I have nearly finished to develop the feature.

About the glossary entries, you prefer to have the string result, or a typed array ?

1- If string, it's the tsv result, without any treatment of the value
2- If array, it can be typed, but you need to implement treatment that can be source of bugs.

What is your review

**Comment by Ciloe** [comment]
I'm facing a problem with the test. Unfortunatly, I get a 401 error on http GET....

This example if the `getSupportedLanguages` already implemented
![image](https://github.com/SC-Networks/deepl-api-connector/assets/1830492/5508f0cf-ff5d-4030-b51f-e79893ccad79)
This example is the `getGlossariesSupportedLanguagesPairs` new implementation that is in 401
![image](https://github.com/SC-Networks/deepl-api-connector/assets/1830492/a05a37dd-d4eb-4030-8a6f-d4fd4fafb4e5)

In the 2 cases, the steam is the same : `auth_key=XXX`

Have you got any ideas ?

This is the RequestHandler : 
```php
<?php

declare(strict_types=1);

namespace Scn\DeeplApiConnector\Handler;

use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\StreamInterface;

final class DeeplGlossariesSupportedLanguagesPairsRetrievalRequestHandler implements DeeplRequestHandlerInterface
{
    public const API_ENDPOINT = '/v2/glossary-language-pairs';

    private string $authKey;

    private StreamFactoryInterface $streamFactory;

    public function __construct(
        string $authKey,
        StreamFactoryInterface $streamFactory
    ) {
        $this->authKey = $authKey;
        $this->streamFactory = $streamFactory;
    }

    public function getMethod(): string
    {
        return DeeplRequestHandlerInterface::METHOD_GET;
    }

    public function getPath(): string
    {
        return static::API_ENDPOINT;
    }

    public function getBody(): StreamInterface
    {
        return $this->streamFactory->createStream(
            http_build_query(
                array_filter(
                    [
                        'auth_key' => $this->authKey,
                    ]
                )
            )
        );
    }

    public function getContentType(): string
    {
        return 'application/x-www-form-urlencoded';
    }
}
```

**Comment by usox** [comment]
> Hi, I have nearly finished to develop the feature.

Hi and Thanks.

I'm look forward to it!

> About the glossary entries, you prefer to have the string result, or a typed array ?
> 
> 2- If array, it can be typed, but you need to implement treatment that can be source of bugs.

If you ask me like that, then I would choose this option.

**Comment by Ciloe** [comment]
@usox the PR is open. I will do the tests after you start a first check of implementation and namings.

Thanks :)

**Comment by usox** [comment]
@Ciloe Thank you very much.

I'll do a few more things tomorrow and then probably release 3.3.

**Comment by Ciloe** [comment]
@usox is it possible to add this feature in the 3.2 version ? (we are still in php version 8.0 and can't update to 8.1)

**Comment by usox** [comment]
@Ciloe Don't worry. I'm going to merge all commits related to the 3.3 milestone in the 3.x branch. As stated in the Readme, 3.x supports 7.4, 8.0, 8.1, 8.2, 8.3.
